---
- hosts: amazonweb
  become_user: root
  become: yes
  tasks:
    - name: 'download java       #task1'
      yum: name=java-1.8.0 state=present update_cache=yes

    - name: 'please install tomcat    #task2'
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.55/bin/apache-tomcat-8.5.55.tar.gz
        dest: /opt

    - name: 'untar file     #task3'
      unarchive:
        src: /opt/apache-tomcat-8.5.55.tar.gz
        dest: /opt
        remote_src: yes

    - name: 'run startup.sh to start tomcat service  #task4'
      command: nohup /opt/apache-tomcat-8.5.55/bin/startup.sh
